// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
declare namespace StylesScssNamespace {
  export interface IStylesScss {
    select: string;
    sort: string;
    sort__description: string;
    sort__value: string;
    sort__value_active: string;
  }
}

declare const StylesScssModule: StylesScssNamespace.IStylesScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesScssNamespace.IStylesScss;
};

export = StylesScssModule;
